name: gravity-ui-release-action

description: |
  Organizes CI/CD pipeline for all Gravity UI packages - generate Changelog and bump version automatically,
  create a release PR which once merged results in creating a new GitHub release and publishing a new version of NPM
  package

inputs:
  node-version:
    description: Node.js version used for running linters, tests, etc
    required: false
    default: '14'
  github-token:
    description: PAT of a GitHub user which creates release PR
    required: true
  npm-token:
    description: PAT of an NPM user which publishes the package
    required: true
  default-branch:
    description: branch to open release PR against (detected by default)
    required: false
  npm-dist-tag:
    description: command for publish npm version
    required: false
    default: 'latest'
  prerelease:
    description: property for prerelease package version
    required: false
  manual-version:
    description: the version of the package that is specified manually
    required: false

outputs:
  release-created:
    description: If the release has been already created or it was just the release PR
    value: ${{ steps.release.outputs.release_created }}

runs:
  using: composite
  steps:
    - run: |
        echo "prerelease: ${{ inputs.prerelease }}"
        echo "npm-dist-tag: ${{ inputs.npm-dist-tag }}"
        if [ "${{ inputs.manual-version }}" != "" && ${{ inputs.prerelease }} == 'true']; then
          if [[ "${{ inputs.manual-version }}" != *"${{ inputs.npm-dist-tag }}"* ]]; then
             echo "Manual version set incorrectly! Check that is contains "${{ inputs.npm-dist-tag }}" in it's name"
            exit 1
          fi
        fi
      shell: bash
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
      shell: bash
    - run: npm test
      shell: bash
    - uses: codex-team/action-nodejs-package-info@v1
      if: inputs.prerelease == ''
      id: package
    - uses: google-github-actions/release-please-action@v3
      if: inputs.prerelease == ''
      id: release
      with:
        token: ${{ inputs.github-token }}
        release-type: node
        package-name: ${{ steps.package.outputs.name }}
        changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"perf","section":"Performance Improvements","hidden":false}]'
        bump-minor-pre-major: true
        default-branch: ${{ inputs.default-branch }}
    - name: Bump and commit prerelease version
      if: inputs.prerelease == 'true'
      run: |
        echo "${{ inputs.manual-version }}"
        echo "${{ inputs.npm-dist-tag }}"
        if [ "${{ inputs.manual-version }}" == "" ]; then
          npm version prerelease --preid=${{ inputs.npm-dist-tag }} --git-tag-version=false
        else
          npm version ${{ inputs.manual-version }} --git-tag-version=false
        fi
      shell: bash
    - name: Extract branch name
      if: inputs.prerelease == 'true'
      shell: bash
      run: |
        echo "branch_name=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"
      id: extract_branch
    - name: Push changes
      if: inputs.prerelease == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
        branch: ${{ env.branch_name }}
    - name: Publish version
      run: |
        echo "steps.release.outputs.release_created: ${{ steps.release.outputs.release_created }}"
        echo "inputs.prerelease: ${{ inputs.prerelease }}"
        npm publish --tag ${{ inputs.npm-dist-tag }} --access public
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
      if: steps.release.outputs.release_created == 'true' || inputs.prerelease == 'true'
      shell: bash
